# redis-external.yaml
# $ kubectl apply -f ./redis-external.yaml
apiVersion: v1
kind: Service
metadata:
  name: redisdb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redisdb
subsets:
  - addresses:
    # FIXME: use the right IP
    - ip: 27.84.196.37
    ports:
      - protocol: TCP
        port: 6379
